### ISSUE TITLE
add firefox support

### ISSUE THREAD

**Issue by alfus5** [lucalewin/better-bing#9]
Hello lucalewin,

I am a Mozilla Firefox user and I recently discovered your Bing extension. I found your extension very useful and I was wondering if it’s possible to make it compatible with Mozilla Firefox.

Thank you in advance for your response.
I hope this helps! Let me know if you need further assistance.

**Comment by lucalewin** [comment]
Hello, thank you for your interest in this project.

You can add the extension to Firefox this way:
- clone (or download) this repo
- open `about:debugging#/runtime/this-firefox` in Firefox
- click `Load Temporary Add-on...`
- select the `manifest.json` from Better Bing

The problem is that you have to do this every time you restart Firefox...
I submitted the extension to the Firefox Addon Store. I'll post a link to it once it is accepted.

**Comment by lucalewin** [comment]
It has been approved!

https://addons.mozilla.org/en-US/firefox/addon/better-bing/

When you open bing.com for the first time after installing the extension you need to click the extension icon in the top left to give the extension the required permissions. You need to right click the extension an then click `Always Allow on www.bing.com`

**Comment by lucalewin** [comment]
I also added the link to the [readme](https://github.com/lucalewin/better-bing#readme)
